baseURL = "https://timothyrenner.github.io/"
languageCode = 'en-us'
title = 'Timothy Renner'
theme = ["github.com/martignoni/hugo-notice", "github.com/adityatelange/hugo-PaperMod"]
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
ignoreFiles = [ "\\.qmd$", "\\.ipynb$", "\\.py$", "\\.csv$", "environment.yml" ]

Paginate = 5
DefaultContentLanguage = "en"

[markup.goldmark.renderer]
unsafe= true

[params]
    author = "Timothy Renner"
    description = "Data and opinions"

    [[menu.main]]
        name = "Blog"
        weight = 1
        url  = "posts/"
    [[menu.main]]
        name = "About"
        weight = 2
        url = "about/"
    [[menu.main]]
        name = "Movies"
        weight = 2
        url = "movies/"
[params.homeInfoParams]
Title = "Welcome"
Content = "I write about data, tech, and mostly dumb stuff."

[[params.socialIcons]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/timothyrenner"
[[params.socialIcons]]
    name = "Instagram"
    icon = "fa fa-instagram fa-2x"
    weight = 1
    url = "https://instagram.com/timothyrenner/"
[[params.socialIcons]]
    name = "Linkedin"
    icon = "fa fa-linkedin fa-2x"
    weight = 1
    url = "https://linkedin.com/in/timothyrenner"
[[params.socialIcons]]
    name = "letterboxd"
    url = "https://letterboxd.com/timothyrenner/"

[module]
[[module.imports]]
path = "github.com/rootwork/hugo-module-gallery-grid"