baseURL = 'https://www.timothyrenner.github.io'
languageCode = 'en-us'
title = 'Timothy Renner'
theme = ["github.com/luizdepra/hugo-coder"]
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

Paginate = 3
DefaultContentLanguage = "en"

[params]
    author = "Timothy Renner"
    description = "Data and opinions"
    [[menu.main]]
        name = "Blog"
        weight = 1
        url  = "/posts/"
    [[menu.main]]
        name = "About"
        weight = 2
        url = "/about/"
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/timothyrenner"
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram fa-2x"
    weight = 1
    url = "https://instagram.com/timothyrenner/"
[[params.social]]
    name = "Linkedin"
    icon = "fa fa-linkedin fa-2x"
    weight = 1
    url = "https://linkedin.com/in/timothyrenner"